on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read patch Note file
        id: getPatchNote
        run: |
            export changelog=$(cat `pwd`/doc/changelog.md)
            changelog="${content//'%'/'%25'}"
            changelog="${content//$'\n'/'%0A'}"
            changelog="${content//$'\r'/'%0D'}"
            echo "::set-output name=changelog::$(echo "$changelog")"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Statique ${{ github.ref }}

          body: |
            ${{ steps.getPatchNote.outputs.changelog }}
            
            # Installation

            Pour pouvoir installer et utiliser statique, consultez le fichier [README](https://github.com/dil-classroom/projet-louis_mondaini_nunez/tree/main#installation)

            # Contributeurs

            Merci à @damianomondaini @NunezTania @hadrylouis pour leurs contributions
          draft: false
          prerelease: false